# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
image: gitpod/workspace-dotnet
tasks:
  - init: echo 'init script' # runs during prebuild
    command: |
      cd src
      docker-compose build
      docker-compose up

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 5104
    onOpen: open-browser
  - port: 5107
    onOpen: ignore
  - port: 5100
    onOpen: ignore
    